### PR TITLE
added an ahk script to the expressvpn package

### PR DESCRIPTION
**Pull request by TakataSanshiro**
For passing chocolatey automated testing.

### CODE REVIEW

**Comment by TakataSanshiro** [comment]
Tested on a local chocolatey test environment.

2018-08-08 13:18:44,187 3064 [INFO ] - Download of expressvpn_6.6.2.4493.exe (25.56 MB) completed.
2018-08-08 13:18:44,187 3064 [INFO ] - 
2018-08-08 13:18:46,853 3064 [INFO ] - Installing expressvpn...
2018-08-08 13:18:46,853 3064 [INFO ] - 
2018-08-08 13:20:02,528 3064 [INFO ] - expressvpn has been installed.
2018-08-08 13:20:02,528 3064 [INFO ] - 
2018-08-08 13:20:02,567 3064 [INFO ] -   expressvpn may be able to be automatically uninstalled.
2018-08-08 13:20:02,685 3064 [INFO ] -  The install of expressvpn was successful.
2018-08-08 13:20:02,685 3064 [INFO ] -   Software installed as 'exe', install location is likely default.
2018-08-08 13:20:02,706 3064 [WARN ] - 
Chocolatey installed 2/2 packages.

**Comment by TakataSanshiro** [comment]
But, I don't test the auto update scripts.

**Comment by Elderry** [comment]
Thanks for your contribution, I'll test it.

**Comment by TakataSanshiro** [comment]
Any update? @Elderry

**Pull request merged**
